### PR TITLE
Adding support for remote server

### PR DESCRIPTION
**Pull request by erez-work**

### CODE REVIEW

**Comment by davidje13** [comment]
I see this relates to #1

Seems reasonable.

A potential gotcha here is that it won't automatically close all connections after each test, so it could be a bit leaky (the existing code registers hooks with the _server_ which track connections and close them when the server is shut down. It's been a while since I worked on it but I seem to remember that turned out a lot easier than tracking it on the client side). Would be good to get your take on that before merging.

**Comment by erez-work** [comment]
Thank you for your reply. I see your point.

In my opinion , it's developer responsibility to close the web socket using the provided `close` function.
However, in case of exception while waiting for a response or sending a message through the socket it needs to be handled to avoid memory leak.

I pushed an update to the PR to close the websocket on such events.
What do you think?
Are there more cases I missed?

**Comment by davidje13** [comment]
I think explicitly closing it at known failures is a good first-line defence, but there are plenty of other ways a test might end:

- user code throws an exception
  - surrounding code unrelated to websockets
  - code which is passed to `expectMessage` / `exec` / etc.
- test times out
- `checkConnectionError`

Code could be added for each of these cases in turn, but realistically I think it's likely something will still be missed and any new code added might forget to close the connection on failure. The worst-case impact I can think of is if somebody ran a test suite in watch mode against a remote server, they would gradually eat-up connections on the server until it eventually can't accept any more (i.e. a slow DoS). Running tests in non-watch-mode wouldn't be so bad because I think NodeJS or the OS itself closes connections cleanly when the process ends.

Generally for this kind of thing my preference is to track and provide a way to reliably tidy up everything. From a user's perspective:

```javascript
it('foobar', () => {
  request('http://example.com')
    .ws('foo')                 // connection is recorded here
    .expectJson({ msg: 'hi' }) // could fail (mismatch), or throw (not json), or test could timeout, etc.
    .close();                  // connection is removed from records since it has explicitly been closed
});

afterEach(() => {
  // guaranteed to clean up any stray connections no matter what happened in the test
  request.closeEverything(); // or whatever it's called
});
```

As I say, your changes look good; just a case of keeping these edge-cases handled. I'll have a go at adding client-side tracking over the next couple of days, then I'll merge this PR.

**Comment by erez-work** [comment]
Sounds good.
Let me know if you want me to help with anything

**Pull request merged**
